laravel:
  build: .
  volumes:
    - laravel_data:/var/www/html
  links:
    - db:db
  ports:
    - 89:80
  restart: always
  environment:
    DB-HOST: db:3306
    DB_USERNAME: root
    DB_PASSWORD: icentra
    DB_DATABASE: laravel
db:
  restart: always
  container_name: mydb
  image: mysql:5.7
  volumes:
    - "/home/user/db:/var/lib/mysql"
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: icentra
    MYSQL_DATABASE: laravel
    MYSQL_PASSWORD: icentra
    MYSQL_TCP_PORT: 3306 
  ports:
      - "3309:3306"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:db
  restart: always
  ports:
    - 8089:80
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_ROOT_PASSWORD: icentra
